const std = @import("std");

const project_version = "1.6.0";
const library_version: std.SemanticVersion = .{ .major = 2, .minor = 4, .patch = 0 };

const library_sources = &.{
    "src/cpxm.c",
    "src/css.c",
    "src/device.c",
    "src/error.c",
    "src/ioctl.c",
    "src/libdvdcpxm.c",
    "src/libdvdcss.c",
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const linkage = b.option(
        std.builtin.LinkMode,
        "linkage",
        "Library linkage: static or dynamic",
    ) orelse .static;
    const build_examples = b.option(
        bool,
        "examples",
        "Build and install the csstest example",
    ) orelse false;
    const warnings_as_errors = b.option(
        bool,
        "warnings-as-errors",
        "Treat C compiler warnings as errors",
    ) orelse false;

    ensureSupportedTarget(target);

    const config_header = makeConfigHeader(b, target);
    const generated = b.addWriteFiles();
    const version_header = generated.add("dvdcss/version.h",
        \\/* Generated by the Zig build. */
        \\#ifndef DVDCSS_VERSION_H_
        \\#define DVDCSS_VERSION_H_
        \\
        \\#define DVDCSS_VERSION_CODE(major, minor, micro) \
        \\    (((major) * 10000) + ((minor) * 100) + (micro))
        \\
        \\#define DVDCSS_VERSION_MAJOR 1
        \\#define DVDCSS_VERSION_MINOR 6
        \\#define DVDCSS_VERSION_MICRO 0
        \\#define DVDCSS_VERSION_STRING "1.6.0"
        \\#define DVDCSS_VERSION \
        \\    DVDCSS_VERSION_CODE(DVDCSS_VERSION_MAJOR, DVDCSS_VERSION_MINOR, DVDCSS_VERSION_MICRO)
        \\
        \\#endif /* DVDCSS_VERSION_H_ */
        \\
    );

    const lib = b.addLibrary(.{
        .name = "dvdcss",
        .linkage = linkage,
        .version = if (linkage == .dynamic) library_version else null,
        .root_module = b.createModule(.{
            .root_source_file = null,
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    configureLibrary(
        b,
        lib.root_module,
        target,
        linkage,
        config_header,
        generated.getDirectory(),
        warnings_as_errors,
    );

    lib.installHeader(b.path("src/dvdcss/dvdcss.h"), "dvdcss/dvdcss.h");
    lib.installHeader(b.path("src/dvdcss/dvdcpxm.h"), "dvdcss/dvdcpxm.h");
    lib.installHeader(version_header, "dvdcss/version.h");
    b.installArtifact(lib);

    const pkg_config = generated.add("libdvdcss.pc",
        \\prefix=${pcfiledir}/../..
        \\libdir=${prefix}/lib
        \\includedir=${prefix}/include
        \\
        \\Name: libdvdcss
        \\Description: DVD access and decryption library
        \\Version: 1.6.0
        \\Libs: -L${libdir} -ldvdcss
        \\Cflags: -I${includedir}
        \\
    );
    const install_pkg_config = b.addInstallFileWithDir(
        pkg_config,
        .lib,
        "pkgconfig/libdvdcss.pc",
    );
    b.getInstallStep().dependOn(&install_pkg_config.step);

    const smoke = addConsumerExecutable(
        b,
        "dvdcss_smoke",
        "test/zig_smoke.c",
        lib,
        target,
        optimize,
        linkage,
    );
    const run_smoke = b.addRunArtifact(smoke);
    run_smoke.expectExitCode(0);
    const test_step = b.step("test", "Build and run the public C API smoke test");
    test_step.dependOn(&run_smoke.step);

    if (build_examples) {
        const csstest = addConsumerExecutable(
            b,
            "csstest",
            "test/csstest.c",
            lib,
            target,
            optimize,
            linkage,
        );
        b.installArtifact(csstest);
    }
}

fn ensureSupportedTarget(target: std.Build.ResolvedTarget) void {
    switch (target.result.os.tag) {
        .linux, .macos, .windows => {},
        else => std.debug.panic(
            "the Zig build currently supports Linux, macOS, and Windows; got {s}",
            .{@tagName(target.result.os.tag)},
        ),
    }
}

fn makeConfigHeader(
    b: *std.Build,
    target: std.Build.ResolvedTarget,
) *std.Build.Step.ConfigHeader {
    const config = b.addConfigHeader(.{
        .style = .blank,
        .include_path = "config.h",
        .include_guard_override = "LIBDVDCSS_CONFIG_H",
    }, .{
        .PACKAGE_VERSION = project_version,
        .HAVE_ERRNO_H = true,
        .HAVE_FCNTL_H = true,
        .HAVE_SYS_STAT_H = true,
        .HAVE_SYS_TYPES_H = true,
    });

    switch (target.result.os.tag) {
        .linux => {
            config.addValue("HAVE_PWD_H", bool, true);
            config.addValue("HAVE_SCSI_SG_H", bool, true);
            config.addValue("HAVE_SYS_IOCTL_H", bool, true);
            config.addValue("HAVE_SYS_PARAM_H", bool, true);
            config.addValue("HAVE_SYS_UIO_H", bool, true);
            config.addValue("HAVE_UNISTD_H", bool, true);
            config.addValue("DVD_STRUCT_IN_LINUX_CDROM_H", bool, true);
            config.addValue("HAVE_LINUX_DVD_STRUCT", bool, true);
            config.addValue("SUPPORT_ATTRIBUTE_VISIBILITY_DEFAULT", bool, true);
        },
        .macos => {
            config.addValue("HAVE_PWD_H", bool, true);
            config.addValue("HAVE_SYS_IOCTL_H", bool, true);
            config.addValue("HAVE_SYS_PARAM_H", bool, true);
            config.addValue("HAVE_SYS_UIO_H", bool, true);
            config.addValue("HAVE_UNISTD_H", bool, true);
            config.addValue("DARWIN_DVD_IOCTL", bool, true);
            config.addValue("SUPPORT_ATTRIBUTE_VISIBILITY_DEFAULT", bool, true);
        },
        .windows => {
            config.addValue("HAVE_IO_H", bool, true);
            config.addValue("HAVE_BROKEN_MKDIR", bool, true);
        },
        else => unreachable,
    }
    return config;
}

fn configureLibrary(
    b: *std.Build,
    module: *std.Build.Module,
    target: std.Build.ResolvedTarget,
    linkage: std.builtin.LinkMode,
    config_header: *std.Build.Step.ConfigHeader,
    generated_headers: std.Build.LazyPath,
    warnings_as_errors: bool,
) void {
    module.addIncludePath(config_header.getOutputDir());
    module.addIncludePath(generated_headers);
    module.addIncludePath(b.path("src"));
    module.addIncludePath(b.path("src/dvdcss"));

    var flags: [12][]const u8 = undefined;
    var count: usize = 0;
    flags[count] = "-std=c17";
    count += 1;
    flags[count] = "-D_DEFAULT_SOURCE";
    count += 1;
    flags[count] = "-Wall";
    count += 1;
    flags[count] = "-Wextra";
    count += 1;

    if (target.result.os.tag != .windows) {
        flags[count] = "-fvisibility=hidden";
        count += 1;
    } else {
        flags[count] = "-D_CRT_SECURE_NO_WARNINGS";
        count += 1;
        flags[count] = "-D_CRT_NONSTDC_NO_WARNINGS";
        count += 1;
        flags[count] = "-D_WIN32_IE=0x0501";
        count += 1;
        flags[count] = "-DWIN32_LEAN_AND_MEAN";
        count += 1;
        flags[count] = "-DPATH_MAX=2048";
        count += 1;
        if (linkage == .dynamic) {
            flags[count] = "-DLIBDVDCSS_EXPORTS";
            count += 1;
        }
    }
    if (warnings_as_errors) {
        flags[count] = "-Werror";
        count += 1;
    }

    module.addCSourceFiles(.{
        .files = library_sources,
        .flags = flags[0..count],
    });

    if (target.result.os.tag == .macos) {
        module.linkFramework("CoreFoundation", .{});
        module.linkFramework("IOKit", .{});
    }
}

fn addConsumerExecutable(
    b: *std.Build,
    name: []const u8,
    source: []const u8,
    lib: *std.Build.Step.Compile,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    linkage: std.builtin.LinkMode,
) *std.Build.Step.Compile {
    const module = b.createModule(.{
        .root_source_file = null,
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    const flags: []const []const u8 = if (target.result.os.tag == .windows and linkage == .dynamic) &.{ "-std=c17", "-DLIBDVDCSS_IMPORTS" } else &.{"-std=c17"};
    module.addCSourceFile(.{
        .file = b.path(source),
        .flags = flags,
    });
    module.linkLibrary(lib);

    return b.addExecutable(.{
        .name = name,
        .root_module = module,
    });
}
